### ISSUE TITLE
Can't control fan for ODD

### ISSUE THREAD

**Issue by patrickgutter2** [crystalidea/macs-fan-control#203]
The manual fan control for the ODD on my iMac 20'' early 2009 can't be controlled. Respectively, if you turn to manual mode, it is not possible to lower the speed.
See screenshot.
I have OSX Version El Capitan 10.11.6 (15G22010)

Any idea?

![Bildschirmfoto 2019-08-18 um 18 26 29](https://user-images.githubusercontent.com/36608915/63227354-cb0fe980-c1e5-11e9-9ea9-5de598db0a88.png)

**Comment by ramsec1** [comment]
The button Manual control is not pressed. There is no access in the program for a choice of turns of the fan. When opening program - there was a prevention that it is impossible to change the fan speed then I cannot in the program change the speed of the fan button do not work. In what a problem? I several times reinstalled the program. But the problem was not solved. Help me.

**Comment by kleuter** [comment]
SMC reset.
