### ISSUE TITLE
Installer hangs on windows 10

### ISSUE THREAD

**Issue by JoueBien** [crystalidea/macs-fan-control#273]
The installer hangs on the Installing phase. The install window hangs and can't be moved. Force closing the installer removes Macs fan control which the installer manages to open before hanging. 

Windows 10 Pro - Ver 1903, OS build 18362.535

![fail 1](https://user-images.githubusercontent.com/7506155/73151935-56889180-4119-11ea-8e3e-7690e515b293.JPG)

**Comment by kleuter** [comment]
Macbook? iMac? Mac Pro? ...

**Comment by JoueBien** [comment]
> Macbook? iMac? Mac Pro? ...

MacBookPro 11,3

**Comment by kleuter** [comment]
Does it happen with 1.5.5?

**Comment by kleuter** [comment]
Please tell me which messages do you see when trying to install this test build, thanks:
https://www.crystalidea.com/downloads/macsfancontrol_setup_debug_init_test.exe

**Comment by zecanard** [comment]
I installed Macs Fan Control on Windows 10 via Boot Camp last week (2019 iMac, 27”), and the installer hung at the very end, with Macs Fan Control running just fine otherwise (it was launched automatically by the installer). After I quit Macs Fan Control from the System Tray, the installation completed normally, and I was able to relaunch the app without issue.

**Comment by kleuter** [comment]
please try this build:
https://crystalidea.com/downloads/macsfancontrol_setup_no_hang.exe

**Comment by kleuter** [comment]
Fixed in the latest build.

**Comment by JoueBien** [comment]
can confirm the latest build now doesn't hang on install

**Comment by kleuter** [comment]
Thanks for confirming!
