### ISSUE TITLE
Setting Max Temperature Below Min Temperature

### ISSUE THREAD

**Issue by zecanard** [crystalidea/macs-fan-control#320]
Macs Fan Control seems to enforce a floor of `Min Temperature + 8°C or 14°F` for a sensor’s Max Temperature. However, that formula only applies if you modify the Min Temperature first. If you open the Sensor Temperature panel and immediately decrease the Max Temperature (without first adjusting the Min temperature), that constraint is not enforced, and you can set the Max to any value—even lower than the Min Temperature.

This is true whether you use the Up/Down buttons or type values directly into the textboxes.

<img width="469" alt="Screenshot 2020-04-25 at 02 42 44" src="https://user-images.githubusercontent.com/25799849/80283438-2b441d00-86dd-11ea-9d0b-5880d8800203.png">

**Comment by kleuter** [comment]
Nice catch, thanks.

**Comment by locofocos** [comment]
This behavior has been the biggest annoyance I've had using this software (and stopped me from buying the full version). Or maybe this is tangential to the original issue: I've tried using this bug to workaround the 14 degree F restriction, sometimes to success, sometimes not. I really, really want a narrower temperature range. I define rules based solely on battery temperature, because my 15 inch macbook pro 2017 seems to let the battery get WAY too hot before the CPU gets hot. I would like the fan to start ramping up at 86 F and reach max speed at about 92 F. The way it works today, I have to define a range from about 82 to 96. That gets me close, but my temp is sitting at 91 F right now and the fans aren't spinning fast enough. But if I raise that range, the fan is spinning very fast at temps like 86, which I don't need.

So, while you're in there releasing 1.5.8...... do you wanna bump that 14 F threshold down to like.... 5? "I'll buy the full version" please?
