### ISSUE TITLE
1.5.8 RC Downloads

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#347]
What's new:

- Display temperature of discrete GPU (eGPU) (#209)
- Improved preferences dialog
- Improved switching between presets from menu bar (#281 )
- Displaying CPU Core (average) on most Apple computers (#235)
- Support of iMac 2020 27" (#382)
- Inverted menubar icon for better dark mode support (#365)
- New main icon (#397 )

Download [macOS](https://crystalidea.com/downloads/macsfancontrol_beta.zip), [Windows](https://crystalidea.com/downloads/macsfancontrol_setup_beta.exe)

**Comment by kleuter** [comment]
The new beta correctly detects connect/disconnect of external eGPU and features improved preferences dialog
![image](https://user-images.githubusercontent.com/2600624/84549020-460f3700-ad07-11ea-8840-036b97886310.png)

**Comment by kleuter** [comment]
Improved switching between presets from the menu bar:

![image](https://user-images.githubusercontent.com/2600624/84817314-04d39b80-b015-11ea-9eeb-e9b0c5aa4568.png)

**Comment by kleuter** [comment]
Latest beta now displays of CPU Core (average) on most models:
![image](https://user-images.githubusercontent.com/2600624/84941237-606b5b00-b0e1-11ea-9926-9127e20011c9.png)

**Comment by zecanard** [comment]
I used to have GPU Diode, GPU PECI, GPU Proximity 1, and GPU Proximity 2 in 1.5.7, but now I only have a single reading GPU Radeon Pro Vega 48. My preset that read from GPU PECI was deleted after launching 1.5.8, and reverting to 1.5.7 did not restore it.

**Comment by kleuter** [comment]
It's true. When discrete GPU option is enabled, all other GPU sensors from SMC are hidden because the option displays the most accurate Core temperature (not proximity).

What is the GPU Diode and GPU PECI temperature in comparison with single reading GPU Radeon Pro Vega 48 (try to turn the option on/off to see the difference).

It's **iMac19,1** I suppose. Thanks.

**Comment by zecanard** [comment]
Yes, iMac19,1. If I _disable_ Discrete GPU support, the other sensor values reappear and line up with the 1.5.7 readings.

The **Radeon Pro Vega 48** reading with Discrete GPU _enabled_ seems to correspond to **GPU Diode**. While idle (screenshots below), the GPU Diode/Radeon Pro Vega 48 reading is significantly lower than the PECI reading; with a game running, GPU Diode pulls up closer to GPU PECI, but remains just a few degrees lower.

Could you explain what exactly **PECI** is? Like many others, I use CPU PECI and GPU PECI as the basis for my fan speeds, since it is usually the highest temperature for the CPU and GPU, respectively.

Thanks.

<img width="821" alt="Screenshot 2020-06-18 at 12 45 32" src="https://user-images.githubusercontent.com/25799849/85055021-90a70e00-b162-11ea-981b-a4c90b5e7697.png">

<img width="821" alt="Screenshot 2020-06-18 at 12 45 42" src="https://user-images.githubusercontent.com/25799849/85055052-9866b280-b162-11ea-99aa-adfe4b7c8a71.png">

<img width="821" alt="Screenshot 2020-06-18 at 12 45 50" src="https://user-images.githubusercontent.com/25799849/85055061-9bfa3980-b162-11ea-8066-1bd3ebed0404.png">

**Comment by kleuter** [comment]
Not sure about it, I would better trust the sensor with GPU name because it uses another technique to correctly display core temperature.

I'm still not sure if it's better to display old GPU SMC sensors. Basically it doesn't make much sense because the list looks overwhelmed and unclear which temperature to use

**Comment by zecanard** [comment]
I’m unsure whether that article is entirely accurate, especially the part claiming that PECI reports the difference between current and throttle temperatures (since that’s not what we observe in Macs Fan Control).

As for the list getting crowded, I agree, and I suspect most users only care about the specific readings they need in order to adjust their fans (one for CPU, one for GPU, one for SSD, etc.). The main issue is knowing which one that is in each case. If it could be made clear to the user which ones are important, hiding SMC sensors may not be necessary (some users will want those values no matter what). Or maybe they could be hidden behind a toggle or expanding tree?

I’m encountering an issue with presets in 1.5.8 beta, in that presets aren’t being read and written correctly. If I save a preset, then immediately click “Based on CPU PECI” again, the temperature triggers change. They also change if I apply a preset, then click “Based on CPU PECI.” Reverting to 1.5.7 displays the correct temperature triggers for all my presets.

Thanks for the update.

**Comment by kleuter** [comment]
Sorry, I didn't understand the problem. Could you please record a video / or make a screenshots to illustrate it? Thanks.

**Comment by zecanard** [comment]
1.5.8 isn’t reading presets, and possibly not saving them either:

![Macs-Fan-Control-Presets](https://user-images.githubusercontent.com/25799849/85151784-d377ed00-b219-11ea-9037-fed9d46d0e24.gif)

**Comment by kleuter** [comment]
Thanks, it was only displayed incorrectly, must be fixed now (please re-download).

**Comment by zecanard** [comment]
New one’s working good 👍🏼
