### ISSUE TITLE
Max RPM differes in macOS and Windows

### ISSUE THREAD

**Issue by fcollingwood** [crystalidea/macs-fan-control#40]
Maximum speed I can set my fans to is 5500RPM. However the fans for this model are rated for, and can can reach 6200RPM. 17" late 2011.

[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/1780060/tech_info.txt)
![screen shot 2018-03-05 at 12 54 53 am](https://user-images.githubusercontent.com/37040349/36945258-0d2a2656-2010-11e8-994f-3c728c021e44.png)

**Comment by kurtzy** [comment]
Greetings fellow owner of what I consider still the world's best laptop =)

I just ran into this issue myself. Fresh install of Win10 and max speed was 5500. In the process, I set my boot partition to macOS, installed/configured macsfancontrol on macOS side, and then reinstalled on Windows side...now max is 6200. What gets presented to Windows via EFI has always been a little crazy on this model, but try messing around and see if you can get good results. Good luck!

**Comment by kurtzy** [comment]
Ok, so my correct fan speed was short lived...back to 5500 now. I think it will require the author to have some sort of override. I'm donating to the cause!

**Comment by kurtzy** [comment]
@fcollingwood I now realize you weren't even talking about bootcamp, so that makes things even more interesting since I don't have a problem in macOS, but I do in Windows...although things seem to be normal when first booting to macOS and then rebooting to Windows.

Here's my info from macOS and Windows:

macOS:

![macbookpro8 3-macos](https://user-images.githubusercontent.com/12423704/36950404-a226a3e6-1fb2-11e8-809a-54fd539b1159.jpg)

[MacBookPro8,3-macos.txt](https://github.com/crystalidea/macs-fan-control/files/1778933/MacBookPro8.3-macos.txt)

Windows:

![macbookpro8 3-windows](https://user-images.githubusercontent.com/12423704/36950422-e3791284-1fb2-11e8-950f-f9816227b576.jpg)

[MacBookPro8,3-windows.txt](https://github.com/crystalidea/macs-fan-control/files/1778935/MacBookPro8.3-windows.txt)

Gotta be some firmware-related thing...hopefully an override is a suitable solution!

**Comment by fcollingwood** [comment]
I don't use, and have never used Bootcamp. Due to that I have only observed this in OS X, and can not comment on Bootcamp symptoms

**Comment by kurtzy** [comment]
Yeah, realized that after reading more closely =)

In your case, wondering if either an SMC reset or forcing max speed through another utility like https://github.com/hholtmann/smcFanControl would work...

**Comment by fcollingwood** [comment]
I've already used smcFanControl and can reach 6200RPM on that. However, it's a little primitive in that my choices are the default temp/speed mappings or a constant defined speed. I use my laptop mainly in clamshell mode sitting in a Henge dock, so temperature is a concern for me. Macs Fan Control is a little more advanced, and I'd like to use the feature where I can define the lower and upper temperatures for minimum and maximum RPM.

**Comment by kleuter** [comment]
According to our database, this model has 5500 under Windows and 6200 under macOS.
The app doesn't change the max fan rpm, but reads it from the SMC.

**Comment by fcollingwood** [comment]
Interesting. Like I said, I don't use bootcamp and don't even have a bootcamp partition, so I have no idea why it only allows me a maximum of 5500RPM

**Comment by kleuter** [comment]
The firmware might change min/max RPM when it thinks it's needed. Not sure when/why it happens exactly.

**Comment by kurtzy** [comment]
Is there any way to force it to 6200 regardless, especially given the track record of this model overheating (https://www.apple.com/support/macbookpro-videoissues/)?

**Comment by kleuter** [comment]
It can be done. But not with the current version of the app.  But you set it manually with this tool:
https://github.com/hholtmann/smcFanControl/tree/master/smc-command

**Comment by kurtzy** [comment]
Looks like that utility only works on macOS...either way, would be great if there could be an override built in for both macOS and Windows for this particular model. Have donated and thanks for the great work!

**Comment by kleuter** [comment]
The utility work in both macOS & Windows. Thanks for the donation!

**Comment by kurtzy** [comment]
Hi, the FAQ for smc-command mentions it won't run in Windows, but that you can set the speed in macOS and then boot to Windows....which isn't much help since doing that already sets things properly to 6200. Just a pain to have to boot macOS first and then Windows rather than Windows directly. Still would be cool if your tool could override directly in Windows. Thanks!
