### ISSUE TITLE
iMac (27in, Late 2009, 11,1 - Quad-Core i7 860) Only 2 cores detected.

### ISSUE THREAD

**Issue by siggyceline** [crystalidea/macs-fan-control#41]
iMac 27in, Late 2009 (11,1)
Quad-Core i7 860 2.80GHz
MacOS 10.13.3 (High Sierra)
Macs Fan Control 1.4.10

Macs Fan Control is only showing two CPU cores on my iMac i7 860 Quad-Core.

![macsfancontrol](https://user-images.githubusercontent.com/37087459/37001163-a0fb9a44-2093-11e8-859a-04aff9559a8c.jpeg)

Menu Meters showing 8 threads:

![menumeter_8_threads](https://user-images.githubusercontent.com/37087459/37001338-35a1bd54-2094-11e8-9ec2-4c0862812415.jpeg)

Log below:

[tech_info.txt](https://github.com/crystalidea/macs-fan-control/files/1788982/tech_info.txt)

**Comment by kleuter** [comment]
SMC reports only 2 cores. Displaying all cores temperature and their temps would be an extra task for us, which requires a device driver. The menu meters app displays virtual cores, and their load (not temp).

**Comment by DOCSISMan** [comment]
Understood on Menu Meters...those are threads.   2 threads/core = 8 threads...which is why it shows eight, and why I posted the pic, in order to validate there are four cores in an i7.

If SMC is reporting only two cores, why does Apple System Report show 4 cores?

There are probably tens-of-thousands of iMac 2010 (11,1) w/i7 still operational out there in the wild.   Be better if you could support them accurately.   The fact is, even though this iMac2010 is eight years old, there is really not much appreciable CPU performance difference from a new iMac doing multi-threaded operations like handbrake encoding.    Folks are keeping their PC's much longer.   I still use a Window 10 PC Core i7 870 as well, and it rocks too.

**Comment by siggyceline** [comment]
Understood on Menu Meters...those are threads. 2 threads/core = 8 threads...which is why it shows eight, and why I posted the pic, in order to validate there are four cores in an i7.

If SMC is reporting only two cores, why does Apple System Report show 4 cores?

There are probably tens-of-thousands of iMac 2010 (11,1) w/i7 still operational out there in the wild. Be better if you could support them accurately. The fact is, even though this iMac2010 is eight years old, there is really not much appreciable CPU performance difference from a new iMac doing multi-threaded operations like handbrake encoding. Folks are keeping their PC's much longer. I still use a Window 10 PC Core i7 870 as well, and it rocks too.
