### ISSUE TITLE
[Big Sur] When enabled: huge spike in CPU usage (kernel_task), UI slowdown and/or freeze 

### ISSUE THREAD

**Issue by schafdog** [crystalidea/macs-fan-control#443]
I am trying to lower the fan speed a bit but not trying to do so aggressively (I think)
When it happens (mostly playing video, but not exclusive) it seems like something in the kernel is going haywire 
UI becomes inresponsive and can freeze. 

If I catch it in time (before freeze) and go back to automatic the CPU usage drops and UI works again.

Attaching techical info file.

**Comment by schafdog** [comment]
[Macs Fan Control log.txt](https://github.com/crystalidea/macs-fan-control/files/5682942/Macs.Fan.Control.log.txt)

The spike happened around 2020-12-12 noon, but may have happened also earlier in the log file.

I started a profile with fans at 50C - 65C. Increased the upper to 70, 75 and last 80. Waited to see if the spike started. First at 80 it seem to begin.

**Comment by schafdog** [comment]
Change the profile to 50-75 and it hasn't happened since I reported. Maybe I was just pushing the envelope too hard.

**Comment by ShayanYaseen** [comment]
Noticed this as well , in fact the cpu temp just froze (maybe) at 70C or so and the mac book became completely hot and shut down on its own . Presumably the app caused the high cpu usage and didn't turn on the fan .

In fact just before shitting down the fan ramped to max rpm . It looks like the mac overheated because of mac fan control -> the app crashed -> mac os regained control of fans and ramped them up but intel shut down the cpu from damage.

I reinstalled the os and removed the app cause this seems as a pretty serious bug. (This happened thrice on the same day)

**Comment by kleuter** [comment]
https://crystalidea.com/macs-fan-control/high-kernel_task_cpu-usage

**Comment by schafdog** [comment]
Sorry for not RTFM ;-D. Will try to get the machine into service and get fans cleaned and new cooling paste. Got my M1 today so it has been demoted. Happened once with the 50-75, but haven't lowered it yet.
