### ISSUE TITLE
Temp display stops reading after a period (MacBookAir6,2/MacBookAir7,2)

### ISSUE THREAD

**Issue by asharpe245** [crystalidea/macs-fan-control#682]
This happens with many of the Macs I installed Fans Control on. for some reason, the temperature display stops updating on the computer. I'll look at it after an hour or so and it's reporting 60 degrees Celsius. if I open the app and change fans control to manual, the correct temp will be displayed. still OK after switching back to Auto mode.

**Comment by kleuter** [comment]
Please post tech info and app screenshot as described at [here](https://github.com/crystalidea/macs-fan-control/blob/master/how-to-post-tech-info.md).

**Comment by ZurboTurbo** [comment]
Sounds like similar behavior I observed in #674.
If you see sensorControl.cpp quit logging entries in the diagnostic log, then you are seeing the same thing I have observed.

**Comment by asharpe245** [comment]
Hi ZurboTurbo,

Thanks for the info. 
Not sure if it matters but I don’t used the sensor based value. This app is on a a computer that I use only occasionally, and I have not been able to re-create the issue since posting. I have seen this many times on a couple of my MacBook Airs.

The cooling and the fans run OK, it’s just that the temperature indicator stops updating while the temp was high, even after 10 minutes or so. Hopefully I will be able to catch this again soon.

Al

On May 13, 2023, at 5:04 AM, ZurboTurbo ***@***.***> wrote:


Sounds like similar behavior I observed in #674 <https://github.com/crystalidea/macs-fan-control/issues/674>.
If you see sensorControl.cpp quit logging entries in the diagnostic log, then you are seeing the same thing I have observed.

**Comment by asharpe245** [comment]
I believe I was able to finally catch this on one of my computers. The screen shot shows the temperature at 44 degrees, but the display showed about 52 degrees for some time previously. the temperature jumped down just as clicked on the screen capture. Files are attached. 
![Screen Shot 2023-05-15 at 5 35 44 PM](https://github.com/crystalidea/macs-fan-control/assets/78440847/02782aa0-ffb9-4098-8de9-5ed906a0d83d)
[MacBookAir7,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11482514/MacBookAir7.2_tech_info.zip)

**Comment by ZurboTurbo** [comment]
This don't look similar to what I was seeing in my logs but your log does have a gap in time where nothing was logged from [2023-05-15 17:12:36:621] to [2023-05-15 17:34:46:652] as if the application was paused possibly after it downloaded an update of fancontrol.xml.gz

[2023-05-15 17:11:35:769] [thread 3680] [Service.cpp#489] Set fans mode 0
[2023-05-15 17:11:35:769] [thread 3680] [FanControl.cpp#276] initialLoadThread finished
[2023-05-15 17:12:35:475] [thread 5555] [UpdateChecker.cpp#169] Updater: downloading https://crystalidea.com/update/fancontrol.xml.gz ...
[2023-05-15 17:12:36:621] [thread 5555] [UpdateChecker.cpp#201] Updater: done (8431 bytes)
**[2023-05-15 17:12:36:621] [thread 5555] [AvailableUpdate.cpp#204] Locale: en**
**[2023-05-15 17:34:46:652] 
/[thread 3056] [Service.cpp#693] getTemperature - skipping sensor TC0E with value of 129.0**
[2023-05-15 17:34:46:652] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TC0F with value of 129.0
[2023-05-15 17:34:46:656] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0F with value of 246.0
[2023-05-15 17:34:46:657] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0R with value of 209.625
[2023-05-15 17:34:46:657] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0V with value of 129.0
[2023-05-15 17:34:46:661] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor Ts0S with value of 129.0

**Comment by asharpe245** [comment]
Hi ZurboTurbo, thanks for getting back to me…

The gap in the logs make me think this is important. When I look at the temperature display, it stays at the same temperature for some time instead of updating every 1-2 seconds as it does normally. This usually occurs while the computer is unattended and often it will stay like this until I do something on the keyboard or open the Macs Fan Control app. This always occurs shortly after start up and may have something to do with an hidden update or possible Spotlight. OS updates are set to manual so it could be Bitdefender or other Apple Store update checking. 

It’s not critical to me but it makes me think the computer is overheating, which is why I have the software. 

It’s a strange one…

Al

On May 28, 2023, at 9:44 AM, ZurboTurbo ***@***.***> wrote:


This don't look similar to what I was seeing in my logs but your log does have a gap in time where nothing was logged from [2023-05-15 17:12:36:621] to [2023-05-15 17:34:46:652] as if the application was paused possibly after it downloaded an update of fancontrol.xml.gz

[2023-05-15 17:11:35:769] [thread 3680] [Service.cpp#489] Set fans mode 0
[2023-05-15 17:11:35:769] [thread 3680] [FanControl.cpp#276] initialLoadThread finished
[2023-05-15 17:12:35:475] [thread 5555] [UpdateChecker.cpp#169] Updater: downloading https://crystalidea.com/update/fancontrol.xml.gz ...
[2023-05-15 17:12:36:621] [thread 5555] [UpdateChecker.cpp#201] Updater: done (8431 bytes)
[2023-05-15 17:12:36:621] [thread 5555] [AvailableUpdate.cpp#204] Locale: en
[2023-05-15 17:34:46:652]
/[thread 3056] [Service.cpp#693] getTemperature - skipping sensor TC0E with value of 129.0
[2023-05-15 17:34:46:652] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TC0F with value of 129.0
[2023-05-15 17:34:46:656] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0F with value of 246.0
[2023-05-15 17:34:46:657] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0R with value of 209.625
[2023-05-15 17:34:46:657] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor TH0V with value of 129.0
[2023-05-15 17:34:46:661] [thread 3056] [Service.cpp#693] getTemperature - skipping sensor Ts0S with value of 129.0

**Comment by ZurboTurbo** [comment]
I agree its an oddball.

Possibly the app was sleeping in your case and did not idle wake back up during that time.

My Mac has been up for three days and I've only seen 4 idle wake ups on fancontrol.
<img width="833" alt="Screen Shot 2023-05-28 at 9 02 49 AM" src="https://github.com/crystalidea/macs-fan-control/assets/127453118/4010af00-455a-41f0-8928-92e640d7838f">

I did not see any entries for sensorControl.cpp in your log but it also only covered a short period of time.
However you are using automatic fan speed control where I am using temperature based so sensorControl.cpp may not come into play on automatic.

Looking back through my log, I am also not observing any time gaps and I also have the same updatechecker lines pulling the same 8k fancontrol.xml.gz update with no pauses afterwards.

I never received any responses on my reported issue but since this seemed similar I certainly wanted to chime in.

**Comment by ZurboTurbo** [comment]
Might be worth looking to see if your instance of MFC has any assertions or recent hangs reported in process viewer.

Select MFC in process viewer then go to View - Inspect process to see the details below:

<img width="841" alt="Screen Shot 2023-05-28 at 9 39 16 AM" src="https://github.com/crystalidea/macs-fan-control/assets/127453118/cd21495f-f2c7-4ca4-a02a-163ea2e2bfc3">

**Comment by asharpe245** [comment]
I would have thought that the “automatic” is merely a sensor setting with a predetermined value in software.
I could give that a try to see if it makes a difference. Unfortunately, the problem doesn’t present itself every time so it could take me a while to see a result. I use it mainly on a MacBook Air that is occasionally use so I’ll have to get it out and try it. 

On May 28, 2023, at 10:29 AM, ZurboTurbo ***@***.***> wrote:


I agree its an oddball.

Possibly the app was sleeping in your case and did not idle wake back up during that time.

My Mac has been up for three days and I've only seen 4 idle wake ups on fancontrol.
 <https://user-images.githubusercontent.com/127453118/241566020-4010af00-455a-41f0-8928-92e640d7838f.png>
I did not see any entries for sensorControl.cpp in your log but it also only covered a short period of time.
However you are using automatic fan speed control where I am using temperature based so sensorControl.cpp may not come into play on automatic.

Looking back through my log, I am also not observing any time gaps and I also have the same updatechecker lines pulling the same 8k fancontrol.xml.gz update with no pauses afterwards.

I never received any responses on my reported issue but since this seemed similar I certainly wanted to chime in.

**Comment by asharpe245** [comment]
I’ll give this a try as well.

On May 28, 2023, at 10:45 AM, ZurboTurbo ***@***.***> wrote:


Might be worth looking to see if your instance of MFC has any assertions or recent hangs reported in process viewer.

Select MFC in process viewer then go to View - Inspect process to see the details below:

 <https://user-images.githubusercontent.com/127453118/241567514-cd21495f-f2c7-4ca4-a02a-163ea2e2bfc3.png>

**Comment by asharpe245** [comment]
Here are some files grabbed today. the computer fan temp showed 73 degrees for about 4-5 minutes, then dropped to 59 degrees, and stayed there until I initiated the log files. at that point it dropped down to about 43 degrees. 
Tell me if you see anything unusual. 

[MacBookAir7,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11585503/MacBookAir7.2_tech_info.zip)
![Screen Shot 2023-05-28 at 12 53 30 PM](https://github.com/crystalidea/macs-fan-control/assets/78440847/980bbdf9-995f-4a83-ab62-a027f882c279)

**Comment by ZurboTurbo** [comment]
Looks like you have the same gap in time after the updater pulls fancontrol.xml.gz.

[2023-05-28 12:39:48:556] [thread 3809] [FanControl.cpp#276] initialLoadThread finished
[2023-05-28 12:40:48:396] [thread 5183] [UpdateChecker.cpp#169] Updater: downloading https://crystalidea.com/update/fancontrol.xml.gz ...
[2023-05-28 12:40:49:850] [thread 5183] [UpdateChecker.cpp#201] Updater: done (8431 bytes)
[2023-05-28 12:40:49:850] [thread 5183] [AvailableUpdate.cpp#204] Locale: en

11 minutes later, the log starts back up again.
[2023-05-28 12:51:37:125] [thread 3174] [Platform_mac_smcwrite.mm#256] process_command_write: SMCWriteKey FS!  0001 OK
[2023-05-28 12:51:37:125] [thread 3174] [Service.cpp#489] Set fans mode 1
[2023-05-28 12:51:37:675] [thread 3814] [Platform_mac_smcwrite.mm#256] process_command_write: SMCWriteKey FS!  0001 OK
[2023-05-28 12:51:37:675] [thread 3814] [Service.cpp#489] Set fans mode 1
[2023-05-28 12:51:37:676] [thread 3814] [Platform_mac_smcwrite.mm#256] process_command_write: SMCWriteKey F0Tg 3624 OK
[2023-05-28 12:51:37:676] [thread 3814] [Service.cpp#346] setFanRPM 13860 for F0Tg
[2023-05-28 12:51:39:181] [thread 3814] [Platform_mac_smcwrite.mm#256] process_command_write: SMCWriteKey F0Tg 3624 OK
[2023-05-28 12:51:39:181] [thread 3814] [Service.cpp#346] setFanRPM 13860 for F0Tg

Certainly would be time to run some tracing on the app to peek further under the hood so to speak.
No hangs or assertions reported but only 7 threads running on yours vs 14 on mine.
Could be expected due to hardware differences.

With linux, i'd be poking around with strace.
I know OSX uses dtrace instead.
Not sure if that would be the best way to go about it though as I would expect there to be a logging verbosity setting for MFC at the command line that may yield more pertinent information on why the app seems to be stalling after pulling the update.

With tracing enabled, it can change timing that can affect app behavior.
Hopefully @klueter can chime in here.

Maybe restarting the Mac in safe mode, killing off any remaining MFC tasks then deleting the app from the applications folder, rebooting and reinstalling would also be a possibility to make sure no files are damaged?

**Comment by asharpe245** [comment]
I decided to run the app in "sensor based" mode and it doesn't pause like it did before. I've always run the app in auto just so I could monitor the temperature. this works better for me now.  I've attached the logs as a comparison.

[MacBookAir7,2_tech_info 31-MAY-23.zip](https://github.com/crystalidea/macs-fan-control/files/11619662/MacBookAir7.2_tech_info.31-MAY-23.zip)

**Comment by kleuter** [comment]
Is this the case?
https://github.com/crystalidea/macs-fan-control/issues/433

**Comment by kleuter** [comment]
If this is the same issue, it can be easily fixed

**Comment by asharpe245** [comment]
I don't think this is the same was the issue I'm having. in my case the computer is running on battery and because i'm using it, the fan and computer don't get a chance to shut down. it does seem to be fine when using the sensor based model.

**Comment by asharpe245** [comment]
OK, thanks. I've downloaded the beta and will give it a try and let your know.

**Comment by asharpe245** [comment]
So far, so good. The temperature continues to update. I notice that this version doesn't auto-start like the release version does. not sure if this is a feature or a bug. 
I've attacher the log for confirmation. 
[MacBookAir7,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11825955/MacBookAir7.2_tech_info.zip)

**Comment by kleuter** [comment]
> I notice that this version doesn't auto-start like the release version does. not sure if this is a feature or a bug.

That's normal.

Thanks!

**Comment by asharpe245** [comment]
So I decided to do a test on another MacBook Air. This time with battery only, no AC adapter. 
The first test sat at 61 degrees for 6 minutes until I clicked on the custom fan speed, at which time it dropped to 46 degrees.
The second test stayed at 74 degrees until again I clicked on custom and it dropped to 43 degree. 
I hope you don't feel there is any pressure from me on this. I'm happy to do the testing if it can help the project. 
Files are attached. 
[MacBookAir6,2_tech_info -1.zip](https://github.com/crystalidea/macs-fan-control/files/11839600/MacBookAir6.2_tech_info.-1.zip)
[MacBookAir6,2_tech_info -2.zip](https://github.com/crystalidea/macs-fan-control/files/11839601/MacBookAir6.2_tech_info.-2.zip)

**Comment by kleuter** [comment]
Oops, I though you have MacBookAir7,2 (according to the first post) and made the workaround for that machine, please try this one now should support 6,2 as well
[macsfancontrol_frozen_readings_fix_2.zip](https://github.com/crystalidea/macs-fan-control/files/11848027/macsfancontrol_frozen_readings_fix_2.zip)

**Comment by asharpe245** [comment]
Oh, that's interesting....  I didn't know the code was hardware specific. I thought it would be an API call to monitor the stats. This beta is working fine on this 2013 MacBook Air. the other computer was a 2017 MacBook Air. 
I've attached the logs for your interest. 
[MacBookAir6,2_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/11851252/MacBookAir6.2_tech_info.zip)
