### ISSUE TITLE
Multi monitor setup - correctly open Macs Fan Control window 

### ISSUE THREAD

**Issue by kleuter** [crystalidea/macs-fan-control#737]
The app should open itself correctly on the monitor where the user clicked the menubar icon.

**Comment by reactive-firewall** [comment]
To prevent duplicates I'll add my details here: maintainers please re-triage if this is a different issue.

Issue: when opening or making Mac Fan Control `active` (ie any action which calls the main window to the front) the window does not correspond to the triggering event's display/screen and seems counter intuitive to some users (like me).

expected behavior: the window is shown on the screen from where the menu item is selected, including intuitively having the window re-position if already visible.


Steps to reproduce behavior: 
- start with a correctly (from MacOS perspective) configured a multi-monitor setup in use. 
- next ensure Mac Fan Control is running with the menubar visible (if not already) 
- select from the menubar the Mac Fan Control menu and activate the "Show Mac Fan Control" sub menu item there-in.
- find and move (manually) the window to be on either display/screen (just need to choose one)
- activate (ie click) the "Hide to menu bar" button of the window
- from the other (ie the un-chosen) display/screen: select from the menubar the Mac Fan Control menu and activate the "Show Mac Fan Control" sub menu item there-in.
- issue presents (end)

This is not the ONLY way to encounter this issue but should simplify reliable testing (I hope)

I've only tested this on `MacOS 14.3` and `MacOS 14.4` 
[MacBookPro16,4_tech_info.zip](https://github.com/crystalidea/macs-fan-control/files/14593944/MacBookPro16.4_tech_info.zip)

hope this helps!
